baseURL = "https://www.fa480.club"
languageCode = "en-us"
theme = "hugo-theme-dream-master"
defaultContentLanguage = "en"
title = "Beats Site"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  author = "BEATS"
  motto = "YOLO"
  # description = ""
  # avatar = ""
  
  # email = ""
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2016
  aboutHeader = "AboutMe"

  paginate = 4

# favicon = "/favicon.ico"
