baseurl = "https://fa480.club"
title = "Beats blog"
author = "BEATS"
paginate = 3
theme = "arabica"

[params]
    description = "A minimal Hugo theme"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "example"
    facebook = "example"
