baseurl = "https://fa480.club"
title = "Beats blog"
author = "BEATS"
paginate = 6
theme = "arabica"

[params]
    description = "Beat's Blog"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "example"
    facebook = "example"
