version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:   
          command: |
            # Setting up docker here.
            cd fa480.club-dockerfile/
            
            # Build 1
            
            docker build --rm=true -t fa480.club-base .
            cd ..
            cd production-site-dockerfile/
            
            # Build 2
            
            docker build --rm=true -t finalbuild -t 507963158957.dkr.ecr.us-west-2.amazonaws.com/beats_repo -t $CIRCLE_SHA1 .
            
            # Tagging
            
            # docker tag finalbuild 507963158957.dkr.ecr.us-west-2.amazonaws.com/beats_repo
            # docker tag finalbuild $CIRCLE_SHA1
            cd ..
      - run:   
          command: |
            # This uploads the ProductionSite.txt to s3.
            sudo pip install awscli        
            aws s3 cp /home/circleci/project/ProductionSite.txt s3://csuneat-project-2/
            sudo rm /home/circleci/project/ProductionSite.txt
      - run:   
          command: |
            # Adding Staging Site to s3.
            touch StagingSite.txt
            echo $CIRCLE_SHA1 > StagingSite.txt
            aws s3 cp StagingSite.txt s3://csuneat-project-2
      - run:
         command: |
           # Upload image to ECR here.
           # aws ecr put-image --image-manifest V2 --repository-name beats_repo --image-tag $CIRCLE_SHA1
           # sudo docker login -u $DOCKER_USER -p $DOCKER_PASS https://507963158957.dkr.ecr.us-west-2.amazonaws.com
           sudo $(aws ecr get-login --no-include-email --region us-west-2) 
           sudo docker push 507963158957.dkr.ecr.us-west-2.amazonaws.com/beats_repo 
            
            
