version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo mkdir ~/blogtozip    
      - run:   
          command: |
            # This way allows you to install hugo with snapd. Takes longer but automatically updated.
            #sudo apt-get update 
            #sudo apt-get install -y snapd
            #sudo snap install hugo
            # This way allows dpkg with a .deb release (will have to be manually updated)
            sudo wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
            sudo apt-get install dpkg
            sudo dpkg -i hugo_0.49_Linux-64bit.deb
      - run:   
          command: |
            cd ~/blogtozip
            sudo hugo new site beats
            sudo mv -v ~/project/hugo-theme-dream-master/ ~/blogtozip/beats/themes/
            sudo mv ~/project/config.toml ~/blogtozip/beats/config.toml
            sudo mv -v /home/circleci/project/* /home/circleci/blogtozip/beats/content
      - run:   
          command: |
            cd ~/blogtozip/beats
            sudo hugo
      - run:
         command: pwd
      - run:
         command: ls
      - run:
          command : |
            tar -zcvf $CIRCLE_SHA1.tar.gz public/  
      - run:
         command: pwd
      - run:
         command: sudo pip install awscli
      - run:
         command: aws s3 cp $CIRCLE_SHA1.tar.gz s3://csuneat-project-2/Uploads/
            
            
            