version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:
          command: pwd
      - run:
          command: ls
      - run:
          command: |
            sudo mkdir ~/project/blogtozip
            sudo mv -v ~/project/hugo-theme-dream-master/* ~/project/blogtozip/
            cd ~/project/blogtozip 
      - run:   
          command: |
            # This way allows you to install hugo with snapd
            #sudo apt-get update 
            #sudo apt-get install -y snapd
            #sudo snap install hugo
            # This way allows dpkg with a .deb release (will have to be manually updated)
            sudo wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
            sudo apt-get install dpkg
            sudo dpkg hugo_0.49_Linux-64bit.deb
      - run:   
          command: |
            sudo mkdir /home/circleci/project/beats/
            cd ~/project/blogtozip
            sudo hugo new site beats
            sudo mkdir ~/project/blogtozip/content/post
            sudo mv ~/project/Week*/* ~/project/blogtozip/content/post
            
            