version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:   
          command: |
            # Setting up docker here.
            cd fa480.club-dockerfile/
            
            # Build 1
            
            echo "build one"
            docker build --rm=true -t fa480.club-base .
            cd ..
            cd production-site-dockerfile/
            
            # Build 2
            
            echo "build two"
            docker build --rm=true -t site .
            
            # Tagging
            
            echo "tagging"
            docker tag site:latest site:$CIRCLE_SHA1
            ls
            cd ..
      - run:   
          command: |
            # This uploads the ProductionSite.txt to s3.
            sudo pip install awscli        
            aws s3 cp /home/circleci/project/ProductionSite.txt s3://csuneat-project-2/
            sudo rm /home/circleci/project/ProductionSite.txt
      - run:   
          command: |
            # Adding Staging Site to s3.
            touch StagingSite.txt
            echo $CIRCLE_SHA1 > StagingSite.txt
            aws s3 cp StagingSite.txt s3://csuneat-project-2
      - run:
         command: |
           # Upload image to ECR here.
           aws ecr put-image --repository-name beats-repo --image-tag site:$CIRCLE_SHA1 
            
            
            
