version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:
          command: pwd
      - run:
          command: ls
      - run:
          command: |
            sudo mkdir ~/project/blogtozip
            sudo mv -v ~/project/hugo-theme-dream-master/* ~/project/blogtozip/
            cd ~/project/blogtozip 
      - run:   
          command: |
            sudo apt-get install -y snapd
            sudo snap install hugo
      - run:   
          command: |
            sudo mkdir /home/circleci/project/beats
            sudo hugo new site beats
            sudo mkdir ~/project/blogtozip/content/post
            sudo mv ~/project/Week*/* ~/project/blogtozip/content/post
            
            