version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run: 
          command: | 
            echo "Initalizing."
            sudo apt-get update && sudo apt-get install -y snapd
            sudo snap install hugo