version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:
          command: pwd
      - run:
          command: ls
      - run:
          command: |
            sudo mkdir ~/project/blogtozip
            sudo mv -v ~/project/hugo-theme-dream-master/* ~/project/blogtozip/
            cd ~/project/blogtozip 
      - run:   
          command: |
            # This way allows you to install hugo with snapd. Takes longer but manually updated.
            #sudo apt-get update 
            #sudo apt-get install -y snapd
            #sudo snap install hugo
            # This way allows dpkg with a .deb release (will have to be manually updated)
            sudo wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
            sudo apt-get install dpkg
            sudo dpkg -i hugo_0.49_Linux-64bit.deb
      - run:   
          command: |
            cd ~/project/blogtozip
            sudo hugo new site beats
            cd ~/project/blogtozip/beats/content/post
       - run:
           command: ls
      - run:   
          command: |
            sudo rm -rf ~/project/blogtozip/beats/content/post/
            sudo mv -v ~/project/Week*/* ~/project/blogtozip/beats/content/post
      - run:
          command: ls
      - run:
          command: |
            cd ~/project/beats
            sudo hugo 
            
            
            