version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:
          command: ls
      - run:
          command: |
            sudo mkdir ~/blogtozip
            mv -v ~/hugo-theme-dream-master/* ~/blogtozip
            cd ~/blogtozip 
      - run:   
          command: |
            sudo apt-get update && sudo apt-get install -y snapd
            sudo snap install hugo
       - run:   
          command: |
            sudo hugo new site beats
            cd ~/
            mv Week*/* ~/blogtozip/content/post
            
            