version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run: 
          command: | 
            ls
            sudo mkdir blogtozip
            sudo mv -v eat-blog/hugo-theme-dream-master/* blogtozip/
            cd blogtozip            
            sudo apt-get update && sudo apt-get install -y snapd
            sudo snap install hugo
            sudo hugo new site beats
            cd ../
            cd eat-blog
            mv * ../blogtozip/content/post
            
            