version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:   
          command: |
            # Get docker here.
            sudo apt-get install docker
            sudo apt-get install docker.io
      - run:   
          command: |
            # This uploads the ProductionSite.txt to s3.
            sudo pip install awscli        
            aws s3 cp /home/circleci/project/ProductionSite.txt s3://csuneat-project-2/
            sudo rm /home/circleci/project/ProductionSite.txt
      - run:   
          command: |
            # Adding Staging Site to s3.
            touch StagingSite.txt
            echo $CIRCLE_SHA1 > StagingSite.txt
            aws s3 cp StagingSite.txt s3://csuneat-project-2
      - run:
          command : |
            # Run docker commands here to create the image
      - run:
         command: |
           # Add $CIRCLE_SHA1 as a tag to docker image here.
      - run:
         command: |
           # Upload image to ECR here.
            
            
            
