version: 2
jobs:
  build: 
    machine: true
    steps:
      - checkout
      - run:   
          command: |
            # Making blog upload directory
            sudo mkdir ~/blogupload
            
            # Getting required packages.
            sudo wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
            sudo apt-get install dpkg
            
            # Installing hugo
            sudo dpkg -i hugo_0.49_Linux-64bit.deb
            
            # Setting up site
            cd ~/blogupload
            sudo hugo new site beats
            sudo mv -v ~/project/arabica ~/blogupload/beats/themes
            sudo mv ~/project/config.toml ~/blogupload/beats/config.toml
            sudo mkdir ~/blogupload/beats/content/post
            sudo mv -v ~/project/* ~/blogupload/beats/content/post
            
            # Building site
            cd ~/blogupload/beats
            sudo hugo
            
            # Removing deb
            cd ~/blogupload/beats
            sudo rm public/hugo_0.49_Linux-64bit.deb
            
      - run:   
          command: |
            # Upload files to S3
            sudo pip install awscli        
            aws s3 cp ~/blogupload/public/* s3://beats480s/
