version: 2
jobs:
  build: 
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: 
        command: | 
          echo "Initalizing."
          sudo apt-get update && sudo apt-get install -y stapd
          sudo snap install hugo